### ISSUE TITLE
Install with npm/yarn is missing files

### ISSUE THREAD

**Issue by W4G1** [wangweiwei/vue-resize-observer#2]
The install from npm doesn't contain any code.

### How to reproduce:
`npm install vue-resize-observer`
or
`yarn add vue-resize-observer`

After installing, only these files are in `node_modules/vue-resize-observer`:

- LICENSE
- package.json
- README.md
- README.zh.md

Where is the code?

**Comment by wangweiwei** [comment]
I'm so sorry that i forgot to build it and I have fixed it in [1.0.26](https://www.npmjs.com/package/vue-resize-observer/v/1.0.26)

**Comment by W4G1** [comment]
Can confirm it works now. Thanks!
