### ISSUE TITLE
vue3 + App.use?

### ISSUE THREAD

**Issue by vinnitu** [wangweiwei/vue-resize-observer#3]
Why it is does not work with vue3?
[demo](https://gist.github.com/vinnitu/d9176040ac3e9cc39ca50c71dbc4cd87)

**Comment by wangweiwei** [comment]
Vue3 will be supported in the next version. @vinnitu

**Comment by wangweiwei** [comment]
@vinnitu it can work with vue3

**Comment by wangweiwei** [comment]
npm install --save vue-resize-observer@next
